# 更新老角色到新角色
UPDATE user_role_relation SET role_code = '第一权限管理员' WHERE role_code = 'firstPermissionSystemAdmin';
UPDATE user_role_relation SET role_code = '项目负责人' WHERE role_code = 'projectManager';
UPDATE user_role_relation SET role_code = '客服负责人' WHERE role_code = 'customerServiceManager';
UPDATE user_role_relation SET role_code = '保洁负责人' WHERE role_code = 'cleanerManager';
UPDATE user_role_relation SET role_code = '保洁' WHERE role_code = 'cleaner';
UPDATE user_role_relation SET role_code = '绿化负责人' WHERE role_code = 'gardenerManager';
UPDATE user_role_relation SET role_code = '绿化' WHERE role_code = 'gardener';
UPDATE user_role_relation SET role_code = '保安负责人' WHERE role_code = 'securityManager';
UPDATE user_role_relation SET role_code = '门岗' WHERE role_code = 'gateSentry';
UPDATE user_role_relation SET role_code = '巡逻岗' WHERE role_code = 'patrolPost';
UPDATE user_role_relation SET role_code = '监控岗' WHERE role_code = 'monitoringPost';
UPDATE user_role_relation SET role_code = '车库岗' WHERE role_code = 'carportSecurity';
UPDATE user_role_relation SET role_code = '工程负责人' WHERE role_code = 'engineeringManager';
UPDATE user_role_relation SET role_code = '工程' WHERE role_code = 'maintainer';
UPDATE user_role_relation SET role_code = '外部维修商' WHERE role_code = 'outsideMaintainer';
UPDATE user_role_relation SET role_code = '财务' WHERE role_code = 'subFinance';
UPDATE user_role_relation SET role_code = '外围观测者' WHERE role_code = 'schrodinger';
UPDATE user_role_relation SET role_code = '苹果审核专用' WHERE role_code = 'toAppStore';
UPDATE user_role_relation SET role_code = '巡更' WHERE role_code = 'patrolExecutive';
UPDATE user_role_relation SET role_code = '业委会' WHERE role_code = 'industry Committee';
UPDATE user_role_relation SET role_code = '管家客服' WHERE role_code = 'customerService';

# 新增以前的客服为前台客服
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '24', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '44', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '57', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '59', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '61', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '71', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '77', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '82', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '104', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '112', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '114', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '192', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '223', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '235', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '253', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '268', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '283', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '285', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '309', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '319', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '401', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '405', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '499', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '571', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '620', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '671', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '680', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '710', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '717', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '723', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '724', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '763', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '770', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '791', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '793', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '821', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '831', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '854', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '870', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '897', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '925', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '933', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '937', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '938', '前台客服');
INSERT INTO user_role_relation(gmt_create, gmt_modify, user_id, role_code) VALUES (now(), now(), '939', '前台客服');

# 删除不用的角色相关关系表
DELETE FROM user_role_relation WHERE role_code IN ('jobAdjustment', 'companyManager', 'energyMeterReader', 'businessExecutive', 'liftWorker');

