# 角色属性表新增所有的角色对应的属性
BEGIN;
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '第一权限管理员', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '项目负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '客服负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '保洁负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '保洁', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '绿化负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '绿化', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '保安负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '门岗', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '巡逻岗', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '监控岗', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '车库岗', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '工程负责人', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '工程', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '外部维修商', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '财务', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '外围观测者', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '苹果审核专用', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '巡更', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '业委会', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '管家客服', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '前台客服', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '保安领班', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '高配', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '弱电', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '行政内务', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '抽检', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '小二', '1', '1', '1', '1');
INSERT INTO role_attribute (gmt_create, gmt_modify, role_code, can_be_bonus_points, can_be_complaint_praise, can_change_zone, can_be_repair_task) VALUES (now(), now(), '物业公司管理员', '1', '1', '1', '1');
COMMIT;

