BEGIN;

# 处理公明物业的所有总部人员
DELETE FROM itl_user_task WHERE user_id = 400;
DELETE FROM itl_user_zone_relation WHERE user_id = 400;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 400, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 640, category_name = '研发部' WHERE id = 400;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 400, 640, '研发部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 400 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '400', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '400', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '400', '总部领导', '87');
DELETE FROM itl_user_task WHERE user_id = 454;
DELETE FROM itl_user_zone_relation WHERE user_id = 454;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 454, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 635, category_name = '市场部' WHERE id = 454;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 454, 635, '市场部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 454 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '454', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '454', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '454', '抽检', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '454', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 502;
DELETE FROM itl_user_zone_relation WHERE user_id = 502;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 502;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 502, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 502 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 618;
DELETE FROM itl_user_zone_relation WHERE user_id = 618;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 618, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 641, category_name = '产品运营部' WHERE id = 618;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 618, 641, '产品运营部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 618 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '618', '行政内务', '87');
DELETE FROM itl_user_task WHERE user_id = 791;
DELETE FROM itl_user_zone_relation WHERE user_id = 791;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 791, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 641, category_name = '产品运营部' WHERE id = 791;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 791, 641, '产品运营部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 791 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '前台客服', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '客服负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '管家客服', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '791', '行政内务', '87');
DELETE FROM itl_user_task WHERE user_id = 1120;
DELETE FROM itl_user_zone_relation WHERE user_id = 1120;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1120, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 641, category_name = '产品运营部' WHERE id = 1120;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1120, 641, '产品运营部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1120 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'businessExecutive', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'carportSecurity', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'cleaner', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'cleanerManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'companyManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'customerService', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'customerServiceManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'energyMeterReader', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'engineeringManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'firstPermissionSystemAdmin', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'gardener', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'gardenerManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'gateSentry', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'industry Committee', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'jobAdjustment', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'liftWorker', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'maintainer', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'monitoringPost', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'outsideMaintainer', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'patrolExecutive', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'patrolPost', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'projectManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'schrodinger', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'securityManager', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'subFinance', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', 'toAppStore', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '业委会', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '保安负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '保洁负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '前台客服', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '后台项目管理员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '外围观测者', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '客服负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '小二', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '巡更', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '工程负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '抽检', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '物业公司管理员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '第一权限管理员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '管家客服', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '绿化负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '苹果审核专用', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1120', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1724;
DELETE FROM itl_user_zone_relation WHERE user_id = 1724;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1724, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 641, category_name = '产品运营部' WHERE id = 1724;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1724, 641, '产品运营部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1724 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '客服负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '抽检', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '行政内务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1724', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1836;
DELETE FROM itl_user_zone_relation WHERE user_id = 1836;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1836, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 636, category_name = '财务部' WHERE id = 1836;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1836, 636, '财务部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1836 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1836', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1836', '总部财务', '87');
DELETE FROM itl_user_task WHERE user_id = 1883;
DELETE FROM itl_user_zone_relation WHERE user_id = 1883;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 1883;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1883 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1888;
DELETE FROM itl_user_zone_relation WHERE user_id = 1888;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1888, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 641, category_name = '产品运营部' WHERE id = 1888;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1888, 641, '产品运营部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1888 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '业委会', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1888', '行政内务', '87');
DELETE FROM itl_user_task WHERE user_id = 1893;
DELETE FROM itl_user_zone_relation WHERE user_id = 1893;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1893, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 638, category_name = '项目管理部' WHERE id = 1893;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1893, 638, '项目管理部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1893 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1893', '抽检', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1893', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1927;
DELETE FROM itl_user_zone_relation WHERE user_id = 1927;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 1927;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1927 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1943;
DELETE FROM itl_user_zone_relation WHERE user_id = 1943;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 1943;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1943 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1947;
DELETE FROM itl_user_zone_relation WHERE user_id = 1947;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1947, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 638, category_name = '项目管理部' WHERE id = 1947;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1947, 638, '项目管理部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1947 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1947', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1952;
DELETE FROM itl_user_zone_relation WHERE user_id = 1952;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1952, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 640, category_name = '研发部' WHERE id = 1952;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1952, 640, '研发部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1952 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '抽检', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '行政内务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1952', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 1957;
DELETE FROM itl_user_zone_relation WHERE user_id = 1957;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1957, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 638, category_name = '项目管理部' WHERE id = 1957;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1957, 638, '项目管理部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 1957 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1957', '总部市场', '87');
DELETE FROM itl_user_task WHERE user_id = 2049;
DELETE FROM itl_user_zone_relation WHERE user_id = 2049;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 2049;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2049 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '巡更', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '抽检', '87');
DELETE FROM itl_user_task WHERE user_id = 2068;
DELETE FROM itl_user_zone_relation WHERE user_id = 2068;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2068, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 638, category_name = '项目管理部' WHERE id = 2068;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2068, 638, '项目管理部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2068 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '总部品质', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '总部市场', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '总部经营', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '总部财务', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '总部领导', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2068', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 2143;
DELETE FROM itl_user_zone_relation WHERE user_id = 2143;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 2143;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2143 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '总部品质', '87');
DELETE FROM itl_user_task WHERE user_id = 2144;
DELETE FROM itl_user_zone_relation WHERE user_id = 2144;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 2144;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2144 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '总部品质', '87');
DELETE FROM itl_user_task WHERE user_id = 2148;
DELETE FROM itl_user_zone_relation WHERE user_id = 2148;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2148, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 637, category_name = '人力资源和行政部' WHERE id = 2148;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2148, 637, '人力资源和行政部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2148 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2148', '总部领导', '87');
DELETE FROM itl_user_task WHERE user_id = 2149;
DELETE FROM itl_user_zone_relation WHERE user_id = 2149;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2149, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 637, category_name = '人力资源和行政部' WHERE id = 2149;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2149, 637, '人力资源和行政部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2149 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2149', '总部领导', '87');
DELETE FROM itl_user_task WHERE user_id = 2150;
DELETE FROM itl_user_zone_relation WHERE user_id = 2150;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2150, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 637, category_name = '人力资源和行政部' WHERE id = 2150;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2150, 637, '人力资源和行政部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2150 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2150', '总部领导', '87');
DELETE FROM itl_user_task WHERE user_id = 2151;
DELETE FROM itl_user_zone_relation WHERE user_id = 2151;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2151, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 637, category_name = '人力资源和行政部' WHERE id = 2151;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2151, 637, '人力资源和行政部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2151 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2151', '总部领导', '87');
DELETE FROM itl_user_task WHERE user_id = 2202;
DELETE FROM itl_user_zone_relation WHERE user_id = 2202;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 639, category_name = '项目品质部' WHERE id = 2202;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 639, '项目品质部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2202 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '总部品质', '87');
DELETE FROM itl_user_task WHERE user_id = 2254;
DELETE FROM itl_user_zone_relation WHERE user_id = 2254;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2254, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 634, category_name = '总经办' WHERE id = 2254;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2254, 634, '总经办', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 2254 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2254', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2254', '总部财务', '87');
DELETE FROM itl_user_task WHERE user_id = 8;
DELETE FROM itl_user_zone_relation WHERE user_id = 8;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 8, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 634, category_name = '总经办' WHERE id = 8;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 8, 634, '总经办', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 8 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '8', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '8', '项目负责人', '87');
DELETE FROM itl_user_task WHERE user_id = 941;
DELETE FROM itl_user_zone_relation WHERE user_id = 941;
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 941, 87);
UPDATE user SET zone_id = 87, zone_ids = '87', category_id = 640, category_name = '研发部' WHERE id = 941;
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 941, 640, '研发部', 87);
UPDATE user SET job_title_id = 19, job_title_name = '总部领导' WHERE id = 941 AND job_title_id < 19;
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '941', '天眼人员', '87');
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '941', '小二', '87');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 13, '工程维修', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 585, '工程部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 601, '工程部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 608, '工程部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 615, '工程部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2202, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2202', '工程', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2202, 622, '工程部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 13, '工程维修', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 585, '工程部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 601, '工程部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 608, '工程部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 615, '工程部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1883, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1883', '工程负责人', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1883, 622, '工程部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '2');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 586, '保安部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 603, '保安部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 610, '保安部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 617, '保安部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1927, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1927', '保安负责人', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1927, 624, '保安部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 11, '绿化', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 587, '环境部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 602, '环境部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 609, '环境部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 616, '环境部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 1943, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '1943', '绿化负责人', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 1943, 623, '环境部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 13, '工程维修', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 585, '工程部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 601, '工程部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 608, '工程部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 615, '工程部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2143, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2143', '工程', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2143, 622, '工程部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 13, '工程维修', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 585, '工程部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 601, '工程部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 608, '工程部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 615, '工程部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2144, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2144', '工程', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2144, 622, '工程部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '2');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '76');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 586, '保安部', 76);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '81');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 603, '保安部', 81);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '82');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 610, '保安部', 82);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '84');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 617, '保安部', 84);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 2049, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '2049', '保安负责人', '85');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 2049, 624, '保安部', 85);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 2);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '2');
INSERT INTO itl_user_category_relation(created_time, modified_time, user_id, zone_category_id, zone_category_name, zone_id) VALUES (now(), now(), 502, 16, '服务中心', 2);
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 76);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '76');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 81);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '81');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 82);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '82');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 84);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '84');
INSERT INTO itl_user_zone_relation(created_time, modified_time, user_id, zone_id) VALUES (now(), now(), 502, 85);
INSERT INTO itl_user_role_relation(created_time, modified_time, user_id, role_code, zone_id) VALUES (now(), now(), '502', '项目负责人', '85');
COMMIT;
