# 公明物业的总部人员
hq_user_list = [
    {'id': '400', 'category': '研发部'},
    {'id': '454', 'category': '市场部'},
    {'id': '502', 'category': '项目品质部'},
    {'id': '618', 'category': '产品运营部'},
    {'id': '791', 'category': '产品运营部'},
    {'id': '1120', 'category': '产品运营部'},
    {'id': '1724', 'category': '产品运营部'},
    {'id': '1836', 'category': '财务部'},
    {'id': '1883', 'category': '项目品质部'},
    {'id': '1888', 'category': '产品运营部'},
    {'id': '1893', 'category': '项目管理部'},
    {'id': '1927', 'category': '项目品质部'},
    {'id': '1943', 'category': '项目品质部'},
    {'id': '1947', 'category': '项目管理部'},
    {'id': '1952', 'category': '研发部'},
    {'id': '1957', 'category': '项目管理部'},
    {'id': '2049', 'category': '项目品质部'},
    {'id': '2068', 'category': '项目管理部'},
    {'id': '2143', 'category': '项目品质部'},
    {'id': '2144', 'category': '项目品质部'},
    {'id': '2148', 'category': '人力资源和行政部'},
    {'id': '2149', 'category': '人力资源和行政部'},
    {'id': '2150', 'category': '人力资源和行政部'},
    {'id': '2151', 'category': '人力资源和行政部'},
    {'id': '2202', 'category': '项目品质部'},
    {'id': '2254', 'category': '总经办'},
    {'id': '8', 'category': '总经办'},
    {'id': '941', 'category': '研发部'}
]
