class JobTitleData:
    JOB_TITLE = [
        {'id': 1, 'name': '项目负责人', 'duties': '', 'type': '项目', 'remark': '项目总经理、项目经理、管理处主任'},
        {'id': 2, 'name': '项目副职', 'duties': '', 'type': '项目', 'remark': '项目副总、项目副经理、项目经理助理'},
        {'id': 3, 'name': '客服负责人', 'duties': '', 'type': '项目', 'remark': '项目客服总监、客服经理、客服主管、客服主任'},
        {'id': 4, 'name': '客服', 'duties': '', 'type': '项目', 'remark': '管家、楼宇管家、前台客服、楼宇客服、综合管理员、综合客服'},
        {'id': 5, 'name': '财务人员', 'duties': '', 'type': '项目', 'remark': '收费员、二级财务、综管员'},
        {'id': 6, 'name': '行政内务', 'duties': '', 'type': '项目', 'remark': '综合管理员、综管员、行政专员、行政人事、综合内务'},
        {'id': 7, 'name': '工程负责人', 'duties': '', 'type': '项目', 'remark': '项目工程总监、工程经理、工程主管、工程主任'},
        {'id': 8, 'name': '工程', 'duties': '', 'type': '项目', 'remark': '水电工、维修工、工程技术员'},
        {'id': 9, 'name': '高配工', 'duties': '', 'type': '项目', 'remark': '高压配电工、高压值班员'},
        {'id': 10, 'name': '弱电工', 'duties': '', 'type': '项目', 'remark': '弱电工程员、弱电技术员'},
        {'id': 11, 'name': '保安负责人', 'duties': '', 'type': '项目', 'remark': '项目保安总监、保安经理、保安主管、保安主任、保安队长'},
        {'id': 12, 'name': '保安领班', 'duties': '', 'type': '项目', 'remark': '保安班长'},
        {'id': 13, 'name': '保安', 'duties': '', 'type': '项目', 'remark': '秩序维护员、安全管理员、护卫队员'},
        {'id': 14, 'name': '环境负责人', 'duties': '', 'type': '项目', 'remark': '环境经理、环境主管、环境主任、环境领班'},
        {'id': 15, 'name': '保洁负责人', 'duties': '', 'type': '项目', 'remark': '保洁经理、保洁主管、保洁主任'},
        {'id': 16, 'name': '保洁员', 'duties': '', 'type': '项目', 'remark': '清洁工、卫生员、晶面技工'},
        {'id': 17, 'name': '绿化负责人', 'duties': '', 'type': '项目', 'remark': '绿化经理、绿化主管、绿化主任、绿化领班'},
        {'id': 18, 'name': '绿化工', 'duties': '', 'type': '项目', 'remark': '绿化技工'},
    ]
